SQLType: mysql
MySQL:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
  username: root
  password: "root"
API-Server:
  adders: localhost
  port: 80

SMTP-Server:
